[package]
name = "near-lake-flows-into-sql"
version = "0.1.0"
edition = "2021"
rust-version = "1.58.1"

[dependencies]
#funty = "=1.1.0"
#bitvec = "=0.20.1"

anyhow = "1.0.51"
#avro-rs = "0.13.0"
base64 = "0.11"
bigdecimal = { version = "0.2", features = ["serde"] }
#borsh = "0.9"
cached = "0.23.0"
dotenv = "0.15.0"
futures = "0.3.5"
hex = "0.4"
itertools = "0.9.0"
mysql_async = "0.29.0"
# syn version conflict, replace with crates.io version once released
#near-sdk = { git = "https://github.com/near/near-sdk-rs", rev="e55f2cf8fed15bbf009851b07c34db0d4814ab04" }
num-traits = "0.2.11"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.55"
#sha2 = "0.9.1"
#sqlx = { version = "0.5.11", features = ["runtime-tokio-native-tls", "mysql", "bigdecimal"] }
#tempfile = "3.3.0"
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1" }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer-primitives = { git = "https://github.com/near/nearcore", rev = "2d7e7f141b387c15cde9a60ed90d64fd0a517c07" }
near-crypto = { git = "https://github.com/near/nearcore", rev = "2d7e7f141b387c15cde9a60ed90d64fd0a517c07" }
near-lake-framework = { git = "https://github.com/near/near-lake-framework", rev = "582c2996b77eb3a2ea96bca839249f55c209a015" }

[patch.crates-io]
mysql_common = { git = "https://github.com/blackbeam/rust_mysql_common", rev = "75b840bf79e7c7849846b5c9eb407d996c060039" }
